Sphinxcontrib-jquery requires sphinx
INFO: pip is looking at multiple versions of sphinxcontrib-jquery to
determine which version is compatible with other requirements.
This could take a while.

ERROR: Could not find a version that satisfies the requirement
Sphinx>=1.8 (from sphinxcontrib-jquery) (from versions: none)

ERROR: No matching distribution found for Sphinx>=1.8