Sphinxcontrib-serializinghtml requires sphinx
INFO: pip is looking at multiple versions of
sphinxcontrib-serializinghtml to determine which version is
compatible with other requirements. This could take a while.

ERROR: Could not find a version that satisfies the requirement
Sphinx>=5 (from sphinxcontrib-serializinghtml) (from versions: none)

ERROR: No matching distribution found for Sphinx>=5